WITH TRIPS AS (

    SELECT  RIDE_ID, 
            -- RIDEABLE_TYPE,
            DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
            TIMESTAMPDIFF(SECONDS,TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS,
            START_STATIO_ID AS START_STATION_ID,
            END_STATION_ID,
            MEMBER_CSUAL AS MEMBER_CASUAL
    FROM {{ ref('stg_bike') }}
    WHERE ride_id != 'ride_id'

)

SELECT * 
    FROM TRIPS